### PR TITLE
Jarvis shortcut changes

### PR DESCRIPTION
**Pull request by ghost**
Changes to shortcuts available on Jarvis
- New Event Log shortcut
- Music files action changes from ActivateWindow(MusicFiles) to ActivateWindow(Music,Files,Return)
- Add 'Files' items to available Music shortcuts
- Update music 'Files' action + add 'Event Log' to inbuilt defaults

Anyone aware of any other Jarvis changes I've missed...?

### CODE REVIEW

**Comment by marcelveldt** [comment]
Uhm, some days ago I noticed a shortcut ActivateWindow(MusicLibrary,blabla). That one isn't working either anymore and is now just ActivateWindow(Music,blahblah). I can't recall if that shortcut was some manually created one or skin shortcuts but better be safe to check

**Comment by ghost** [comment]
Thanks. I'll double-check everything skin shortcuts creates to ensure there's no 'MusicLibrary' links in there (and maybe add a note to the docs for skinners to be aware of pre-Jarvis actions in their default shortcuts).

Though, when I thought it was just the 'Files' action that had changed, I was happy enough to say that users could just re-create that. If there are multiple music library shortcuts that are being broken, it may be better to upgrade them on-the-fly when the shortcuts are loaded...

**Comment by ghost** [comment]
Updated PR to upgrade 'old' music shortcuts (`ActivateWindow(MusicLibrary...` + `ActivateWindow(MusicFiles)`) to Jarvis-era actions (and thanks again for pointing that out marcelveldt) - and also updated the visibility conditions.

Any other changes to Jarvis shortcuts needed...?

**Comment by ghost** [comment]
Fixed one more case of the script returning shortcuts with MusicLibrary and not Music, and added shortcuts + music playlist option for Party Mode.

At this point I'm going to merge this, and will deal with any other changes needed for Jarvis as-and-when they are brought up.

**Comment by marcelveldt** [comment]
Great!

**Pull request merged**
