### PR TITLE
Hide home button if on home

### PR DESCRIPTION
**Pull request by BADMS**
I can't see a way to create a custom 'visible' for menu items, so in this case the home button is useless on homepage. IF there is a way to do this then ignore [apart from making another menu just for home?].

### CODE REVIEW

**Comment by ghost** [comment]
```
<override action="ActivateWindow(Home)">
    <condition>!Window.IsVisible(Home)</condition>
<override>
```

**Comment by BADMS** [comment]
I tried the code, it has no affect. I still see items on homepage with the overrides set in overrides.xml?

**Comment by ghost** [comment]
Sorry this has taken me so long to look at. The code snippet I provided works for me, so can you please provide a full debug log, an overrides.xml showing the proposed solution in place and a built script-skinshortcuts-includes.xml that shows that you still have the issue with the proposed workaround in place.

Once I've received and reviewed that, I'll happily merge this as a workaround to a bug I can't reproduce :)

**Comment by ghost** [comment]
Is this PR still relevant?

**Comment by BADMS** [comment]
sorry, forgot this. will check when possble thanks

**Pull request closed without merging**
