### PR TITLE
adds shortcuts dialog for the edit action function. 

### PR DESCRIPTION
**Pull request by marcelveldt**
As discussed here: https://github.com/BigNoid/script.skinshortcuts/issues/17

@Ignoble61 will you do the code review and merge ?

### CODE REVIEW

**Comment by ghost** [comment]
Can the keyboard dialog for custom action have the current action pre-filled? (This is a feature I use fairly regularly, and completely retyping custom actions would be a huge pain!)

Also, as the button action is now to select an action, should the default label for the button be updated? (currently 32027 - 'Custom action')

**Comment by marcelveldt** [comment]
you're right. Updated it. Thanks

**Comment by ghost** [comment]
Possible to squash your commits? Otherwise, with the one line comment above, this looks good to go.

**Comment by ghost** [comment]
Sorry, two more little things - ~~if no path is returned (path = "") then the saved action should be "noop"~~ (my bad, not possible to return no action there), and the returned path should probably be try_decode()'d.

**Comment by marcelveldt** [comment]
OK, squashed the commits and fixed your recommendations

**Comment by ghost** [comment]
D'you mind taking one more pass at that squash - you managed to squash it into more commits than it started with ;) (If you're anything like me, you'll have forgotten to `push -f` after the `rebase -i` - I can't count how many times I've done that!)

**Comment by ghost** [comment]
I might be jumping the gun, and I certainly don't want to patronise, but my expectation was you'd squash commits nice and quickly, so if you need any help/guidance in doing so, please let me know :)

**Comment by ghost** [comment]
@marcelveldt let me know what you want doing with this PR. If you'd prefer not to squash (or the commits can't be squashed, or so on) then just say and let's get it merged (it's just my personal preference to have things like this as a single commit where possible.) Cheers :)

**Comment by marcelveldt** [comment]
Commits are (finally) squashed!

**Comment by ghost** [comment]
Great, can finally rebase on this :) (gets me one step, of only a couple of steps left, to PR'ing the new widgets!)

**Comment by marcelveldt** [comment]
Nice!

**Pull request merged**
