### PR TITLE
Adjust Isengard + earlier music addon shortcut dependant on music lib…

### PR DESCRIPTION
**Pull request by ghost**
…rary on Isengard and earlier

As originally reported:- http://forum.kodi.tv/showthread.php?tid=252302, with condition for action provided by Ronie here:- http://forum.kodi.tv/showthread.php?tid=178294&pid=2198065#pid2198065

Needs confirming that non-working music add-ons are being accessed via a Music Add-ons shortcut, and that the fix works. Worth considering a repo push to get this fix out before Isengard becomes old news...?

### CODE REVIEW

**Comment by ghost** [comment]
Thinking through this, this will only affect the shortcut at menu build time - if the boolean condition changes after that, the menu item will not update. Therefore this either needs handling in a different way (at present there's no mechanism to add a second action to a shortcut dependant on what the action is, which is what would be needed...) or we need to rebuild the menu on the boolean condition change (can be handled with the .hash file).

**Comment by ghost** [comment]
Updated to also adjust action for shortcuts to specific music addons based on whether there is music content, and to rebuild the menu if music content has changed. (All Isengard only)

**Comment by marcelveldt** [comment]
Is this ready to test ? Sorry for the late feedback. I was ill for the last couple of days and besides that busy with family.

BTW: Happy new year to you and your family

**Comment by ghost** [comment]
I'd like to confirm whether the changes to shortcuts directly to music addon nodes are needed - but it's the wrong time of year for this sort of thing so haven't got round to testing it yet :)

Hope you're feeling better, and that 2016 brings great things to you and yours.

**Pull request merged**
