### PR TITLE
Initial Python 3 support

### PR DESCRIPTION
**Pull request by mooninite**
First: Where is the version 1.0.19 code? This code repo does not appear up-to-date.

Second: Please consider re-writing this add-on. It's code style needs a serious overhaul.

This is an initial stab at adding Python 3 support. You will need this to get this add-on working with Kodi 19.

Fedora 32 is using a Kodi 18 compiled with Python 3 so I would like to get this add-on updated and pushed to the Kodi 18 repo.

### CODE REVIEW

**Comment by Ch1llb0** [comment]
There's already a Pyhton v3 compatible fork to be found here: https://github.com/mikesilvo164/script.skinshortcuts/tree/python_3

Discussion about it can be found here: https://forum.kodi.tv/showthread.php?tid=178294&pid=2923729#pid2923729

**Comment by mooninite** [comment]
Releasing code should not be done in a web forum. I had no idea that code branch existed.

1. The Kodi website does not link to that repo. It links to this repo.
2. I don't watch the web forum every day. I may visit once every 3 months.

While I am grateful that the add-on is being worked on when will the code be released? Fedora 32 uses Python 3 and the released version of this add-on does not work. @mikesilvo164

**Comment by MikeSiLVO** [comment]
Hmm... Not the best attitude to have with volunteer open source projects IMHO. Code can be released however someone wants to release it. The fact you didn't know of the existence of that branch because of your lack of time in keeping up the forum, where I originally posted for help, has nothing to do with me or the release of a testing version there.

The python_3 branch is many months old and master branch is the most current python 3 compatible version. A version was already released in the Kodi Matrix Repo but master branch has some bug fixes not yet pushed.

I have been working on adding Skin Shortcuts to Kodi repo since March 9th and it was added about 15 days ago
https://github.com/xbmc/repo-scripts/pull/1338

**Comment by mooninite** [comment]
Thanks for the update.

**Comment by Ch1llb0** [comment]
> The python_3 branch is many months old and master branch is the most current python 3 compatible version. A version was already released in the Kodi Matrix Repo but master branch has some bug fixes not yet pushed.

My bad, I should've stated this correctly. Thanky you for your great work, @mikesilvo164! 👍

**Pull request closed without merging**
