### PR TITLE
Apply all additional overrides to visibleoverride's

### PR DESCRIPTION
**Pull request by ghost**
Ping @sualfred 

Sorry this has taken me so long to get to but hopefully this fulfils your request detailed in #190. I'd appreciate it if you could test to see if it does what you require. If not, samples of your overrides and what output you got for those overrides in your includes file would be appreciated.

### CODE REVIEW

**Comment by sualfred** [comment]
No need for sorry :) Your free time, not mine.

Thanks for taking care of it, but it doesn't work.

Result:

```
 <item id="3">
            <property name="id">$NUMBER[3]</property>
            <label>$LOCALIZE[342]</label>
            <label2>Common Shortcut</label2>
            <icon>DefaultMovies.png</icon>
            <thumb>special://skin/extras/shutdown/</thumb>
            <property name="labelID">movies</property>
            <property name="defaultID">movies</property>
            <property name="widgetName">Widget Group 1</property>
            <property name="widget">widget1</property>
            <property name="ftvWidget">widget1</property>
            <onclick condition="Control.IsVisible(91)">noop</onclick>
            <property name="path">noop</property>
            <property name="list">noop</property>
            <onclick condition="Control.IsVisible(91)">noop</onclick>
            <onclick condition="Control.IsVisible(91)">noop</onclick>
            <onclick condition="Control.IsVisible(91)">noop</onclick>
            <visible>StringCompare(System.ProfileName,Master user)</visible>
            <property name="submenuVisibility">movies</property>
            <property name="group">mainmenu</property>
            <property name="hasSubmenu">True</property>
        </item>
```

Used override setting:

```
<visibleoverride condition="Library.HasContent(Movies)">ActivateWindow(Videos,Files,return)/visibleoverride>
    <override action="globaloverride" group="mainmenu">
        <condition>!Control.IsVisible(91)</condition>
    </override>
    <override action="globaloverride" group="mainmenu">
        <condition>Control.IsVisible(91)</condition>
        <action>noop</action>
    </override>
```

**Comment by ghost** [comment]
Free time? What's that???

Thanks for the samples. can you please try the update.

**Comment by sualfred** [comment]
Dunno, I'm a young father. That means that free time sounds like a fantasy novel to me ;)

Seems to work.  Thanks!

Result:

```
        <item id="2">
            <property name="id">$NUMBER[2]</property>
            <label>$LOCALIZE[19019]</label>
            <label2>Live-TV</label2>
            <icon>DefaultTVShows.png</icon>
            <thumb />
            <property name="labelID">19019</property>
            <property name="defaultID">19019</property>
            <property name="translatedPath">ActivateWindow(TVChannels)</property>
            <property name="widgetName">TV</property>
            <property name="widget">livetv</property>
            <property name="widgetType" />
            <property name="widgetPath" />
            <property name="widgetTarget" />
            <property name="ftvWidget">livetv</property>
            <onclick condition="[System.HasPVRAddon] + [!Control.IsVisible(91)]">ActivateWindow(TVChannels)</onclick>
            <property name="path">ActivateWindow(TVChannels)</property>
            <property name="list">TVChannels</property>
            <onclick condition="[![System.HasPVRAddon]] + [!Control.IsVisible(91)]">RunScript(script.skin.helper.service,action=dialogok,header=$LOCALIZE[257],message=$LOCALIZE[31327])</onclick>
            <onclick condition="[System.HasPVRAddon] + [Control.IsVisible(91)]">noop</onclick>
            <onclick condition="[![System.HasPVRAddon]] + [Control.IsVisible(91)]">noop</onclick>
            <visible>StringCompare(System.ProfileName,Master user)</visible>
            <property name="submenuVisibility">num-19019</property>
            <property name="group">mainmenu</property>
            <property name="hasSubmenu">True</property>
        </item>
        <item id="3">
            <property name="id">$NUMBER[3]</property>
            <label>$LOCALIZE[342]</label>
            <label2>Common Shortcut</label2>
            <icon>DefaultMovies.png</icon>
            <thumb>special://skin/extras/shutdown/</thumb>
            <property name="labelID">movies</property>
            <property name="defaultID">movies</property>
            <property name="widgetName">Widget Group 1</property>
            <property name="widget">widget1</property>
            <property name="ftvWidget">widget1</property>
            <onclick condition="[Library.HasContent(Movies)] + [!Control.IsVisible(91)]">ActivateWindow(Videos,MovieTitles,return)</onclick>
            <property name="path">ActivateWindow(Videos,MovieTitles,return)</property>
            <property name="list">MovieTitles</property>
            <onclick condition="[![Library.HasContent(Movies)]] + [!Control.IsVisible(91)]">ActivateWindow(Videos,Files,return)</onclick>
            <onclick condition="[Library.HasContent(Movies)] + [Control.IsVisible(91)]">noop</onclick>
            <onclick condition="[![Library.HasContent(Movies)]] + [Control.IsVisible(91)]">noop</onclick>
            <visible>StringCompare(System.ProfileName,Master user)</visible>
            <property name="submenuVisibility">movies</property>
            <property name="group">mainmenu</property>
            <property name="hasSubmenu">True</property>
        </item>
```

**Comment by ghost** [comment]
When it gets to grand-parenting, the free time goes out of the window a second time ;)

Thanks for testing. Closes #190

**Pull request merged**
