### PR TITLE
End user-focused changes

### PR DESCRIPTION
**Pull request by ghost**
These commits are various changes to the script primarily aimed at the end users, unlike most commits which are normally requested by skinners.
- Context menu extension point (enabled from settings) to add any folder directly to the home menu, including auto-filling the submenu
- Language changes, moving away from referring to 'shortcuts' towards 'menu items', also should clear up some functions (choose shortcut/change action)
- Add option not to hide PVR shortcuts (requested feature)
- Use mtime, not hash of file, to determine if .DATA.xml/property files/overrides/etc have changed - should reduce disk access significantly
- Oft requested feature, the ability for users to specify that their menus aren't shared amongst skins utilising the script, plus ability to import menu from another skin
- Fix for disappearing icons between skins - icons and thumbs are now saved in the skins .properties file

Also bumps version and docs to mark unstable.

Context menu required xbmc.python 2.20.0 (Isengard), but I believe the script is on the Isengard repo...?

The non-sharing skins feature requires changes to skin.helper.service's backup functions, which I will PR separately.

The language changes will probably only be effective if the script is added onto Transifex.

@marcelveldt do you have time to give these changes a look through?

### CODE REVIEW

**Comment by phil65** [comment]
Would be nice if you could move the context menu extension to a separate add-on. That way users can choose if they want it (otherwise the context menu becomes very cluttered quickly)

**Comment by ghost** [comment]
It's currently a setting and disabled by default, in an attempt to avoid having to actually request a new add-on to the repo ;) but I'll move it into a separate add-on tomorrow :)

**Comment by phil65** [comment]
Ah ok, that might also work. I think it´s nicest though if all additional entries are listed in context menu section from add-on manager. If you agree: cool. If not: also fine.

**Comment by ghost** [comment]
Moved context menu to separate addon - https://github.com/Ignoble61/context.skinshortcuts.addtomenu - as @phil65 suggests.

**Comment by guidosarducci** [comment]
@Ignoble61  These are very welcome changes -- thank you!  I had previously been trying out the non-shared menu changes from your UX branch, but suggest making non-shared menus the default addon setting since it is much less frustrating for users.

For example, a common case is when a long-time skin user tries to test-drive a new skin, does some simple configuration, but then returns to the old skin to find the original menus messed up.  I also want to mention that in the 4-5 skinshortcut-enabled skins where I've tweaked menus to my liking, the menus ended up different between the skins, again making non-shared menus preferable.

**Comment by ghost** [comment]
It will not be enabled by default in this version as that would cause everyone's menus to reset to default. It is something that could be discussed for a future version as the setting would then only take effect for new installations.

If people are experiencing menu's being "messed up" it is more preferable to post a debug log + screenshots of the issue so it can be fixed than for Skin Shortcuts to just disable the shared menu's by default. The only issue with shared menu's I'm currently aware of (which is to say has been reported on the forums) is with icons disappearing between skins, and this branch contains a fix for that issue.

**Pull request merged**
