### PR TITLE
Custom property improvements & minor fixes

### PR DESCRIPTION
**Pull request by ghost**
Improvements to the ability to set custom properties
- New `<propertySettings />` element - to set the dialog title, whether ‘None’ will be shown and to enable image browsing
- buttonID attrib in propertySettings, to tell script to handle additional button to set the custom property (no more having to set a window property then send a click to 404)
- New label attrib for `<property />` element - to set label to display separately from value (will also translate $INFO’s) and condition attrib to decide if property should be shown
- Localise strings
- Clear window property ‘chooseProperty’ after sendClick to 404
- Update documentation

This has been tested by @Jayz2K via the Kodi forums, and should implement most of the requests in #57 (except default value for new items)

### CODE REVIEW

**Comment by ghost** [comment]
I've added a small fix if that's OK, rather than opening a new PR for it. As reported on the forum (or will be reported, when they sort out their debug log), it fixes a condition whereby the action can be blank if the user edits the shortcut. This fix ensures that if the custom action is empty, it gets set to "noop".

**Comment by ghost** [comment]
Again, doesn't seem worth opening a PR for one line of code, so another commit which - finally and completely - fixes cases where one profiles properties can be applied to another profiles menus, by clearing the cache of custom properties when the profile we're building the menu for changes.

**Comment by marcelveldt** [comment]
This is looking fine to me. It has also been reported as working and not breaking stuff :-)

**Comment by ghost** [comment]
Cheers :)

**Pull request merged**
