### PR TITLE
Build empty templates if not matched

### LINKED ISSUE #142: Low prio: Write empty includes
http://forum.kodi.tv/showthread.php?tid=259210&pid=2239242#pid2239242

When using templates, the XML code is built when needed (the shortcut has condition X or Y).
This works fantastically well for writing widgets to the homemenu and even multiple widgets.

However if the condition is not true for a shortcut, the include is not written at all in the skin, causing some missing include errors in the logs.

For example, in Titan each shortcut can have up to 4 widgets and an include is set for each templated include. Well, when the user only assigned one widget a warning is written to the log.

This error could be prevented ny writing an empty xml element to skin for the include.

Definitely low prio as it's only a warning in the log and does no harm.
I'll look into it myself on a rainy day so this is just a reminder.

### PR DESCRIPTION
**Pull request by ghost**
As discussed in #142 this writes empty includes for any template that isn't built by matching to menu items, avoiding any Skin Has Invalid Includes errors in log.

@marcelveldt hope you don't mind that I went ahead and wrote this, but there are more skins switching to templates so it would be nice to get this feature onto the repo sooner than later. Are you happy with the way I've implemented it?

Closes #142

### CODE REVIEW

**Comment by marcelveldt** [comment]
haha, you've beaten me to it. Was going to take a look at it one of these days ;-)
Code looking fine, no problems merging this in. Thanks!

**Comment by ghost** [comment]
Cheers. How do you feel, when we know whether #149 is going in, doing a repo push so that the skins adopting templates won't have problems with the mailing list (and so the mailing list find it easier, of course)?

Only one new feature, the rest bug fixes so if a beta period is needed it shouldn't need to be a long one!

**Comment by marcelveldt** [comment]
A repo push sounds good to me. Want to do it now or first revert the temp krypton code ?

**Comment by ghost** [comment]
My reading right of Phil's PR means that the Krypton change won't be necessary, so I say get the reversion in and - if necessary - it can be un-reverted later.

I'd also say get getting-rid of the music library visibility conditions in too. Are you happy doing that?

**Comment by marcelveldt** [comment]
OK, sounds great. I will fix the music visibility then and afterwads we can do another repo pull

**Pull request merged**
