### PR TITLE
Warn on disabling menu item and update PVR visibility

### PR DESCRIPTION
**Pull request by ghost**
Updates the disable shortcut function to honour the same warning dialog as when deleting it, as requested in #189. Also fixes issue mentioned in PR when menu build will be triggered when the warning dialog to delete a shortcut is cancelled.

Ping @mikesilvo164 to test, and apologies this has taken me so long to get around to.

Also updates PVR visibility conditions to new 'System.HasPVRAddon'.

### CODE REVIEW

**Comment by MikeSiLVO** [comment]
@Ignoble61 No apologies necessary Sir Bob :smiley:

Unfortunately, for me, the disable function no longer works and i get this in the Kodi log

```
> 15:47:30 T:10876   DEBUG: script.skinshortcuts: Toggle disabled (313)
15:47:30 T:10876   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.UnboundLocalError'>
Error Contents: local variable 'num' referenced before assignment
Traceback (most recent call last):
  File "C:\Users\SiLVO\AppData\Roaming\Kodi\addons\script.skinshortcuts\resources\lib\gui.py", line 2318, in onAction
    self._display_Context_Menu()
  File "C:\Users\SiLVO\AppData\Roaming\Kodi\addons\script.skinshortcuts\resources\lib\gui.py", line 2351, in _display_Context_Menu
   self.onClick( contextActions[ selectedItem ] )
  File "C:\Users\SiLVO\AppData\Roaming\Kodi\addons\script.skinshortcuts\resources\lib\gui.py", line 1777, in onClick
  if self.warnonremoval( listControl.getListItem( num ) ) == False:
UnboundLocalError: local variable 'num' referenced before assignment
 -->End of Python script error report<--
```

Hmmm. Whats the best way to post log snippets? Not used to markdown yet...

**Comment by ghost** [comment]
That's fine for a quick snippet. Silly mistake on my part, can you please try again.

**Comment by MikeSiLVO** [comment]
Didn't notice any issues. I checked disabling both a regular and submenu item through the context menu as well as button 313.

Thank you Sir! 😄

**Comment by ghost** [comment]
And thank you for testing. Closes #189

**Pull request merged**
