### PR TITLE
Remove library editor integration

### PR DESCRIPTION
**Pull request by ghost**
Removes all integration with video/library node editor scripts.

### CODE REVIEW

**Comment by marcelveldt** [comment]
Huh? Was the pr denied?

**Comment by ghost** [comment]
Doesn't matter. Knowing who has taken over day-to-day of that script, I'm not going to get into any situation where I'm working with them. If you want to undo the changes/make the relevant changes to the other script you're more than welcome. It's not something I'll get involved with.

**Comment by BigNoid** [comment]
Whats going on. I wasnt involved here so please lets try again :)

**Comment by ghost** [comment]
There is a good reason I wasn't involved with Kodi for 6 months+. If people want to try again that's great, but it won't involve me :)

(And lets be clear I'm not blocking this at all - if I didn't think these were good changes, I wouldn't have proposed them in the first place. And for those willing to PR them against those who I have found, shall we say, negative, those changes are still available via the original PR's.)

**Comment by BigNoid** [comment]
@Ignoble61  Please contact me @ big.noid@kodi.tv

**Comment by ghost** [comment]
Sorry, but I have learnt to keep things public. Communicate with me here, or not at all :)

**Comment by BigNoid** [comment]
okay fair enough :) You dont have to deal with team-kodi as a whole. Contact me if there's anything

**Comment by BigNoid** [comment]
i mean contact in public ofc if thats your preference

**Comment by ghost** [comment]
I believe I've made my position clear - I don't trust the individual who has taken over day-to-day of the node editor script, so have removed integration from the skin shortcuts script (whilst making clear that anyone who wants to re-integrate the scripts is welcome and, more than that, will have my support - assuming they are not the original individual who causes me to remove said integration - and, as such, would have the code to do so quite easily.

Let me make it very clear there are many Kodi team members who I do trust - yourself included - and I'm sorry the situation has come to this. My intention - as I hope indicated by my attitude both here and 6 months ago, was never to identify those who disagreed with my coding.

**Pull request merged**
