### PR TITLE
Add custom property fallback value override

### PR DESCRIPTION
**Pull request by ghost**
An often-requested feature since all the muchly-improved custom property stuff, this adds the ability to specify a default value (or 'fallback') to set a custom property to if the user hasn't selected a value.

I can't remember exactly who has requested this, but I think both @tomer953, @Jayz2K and @mistervee all have - if that's right, are any of you in a position to test it before it gets merged...?

### CODE REVIEW

**Comment by tomer953** [comment]
Actually I asked for it, but i'm very busy those days, I'm hope to be able to test it tomorrow.
thanks.

**Comment by ghost** [comment]
No rush. Any time you can spare is appreciated :)

**Comment by ghost** [comment]
@tomer953 I know I said no rush, but is it likely you'll be able to test this weekend? If not, I'm tempted to just get them merged and we'll deal with issues if they arise (I've tested these myself, so I'm keeping my fingers crossed that they will 'just work' :wink:)

**Comment by tomer953** [comment]
Sorry I've been away for the whole week.
I can confirm its working in my end.

**Comment by ghost** [comment]
No need to be sorry, real life always comes first :)

Thanks for testing.

**Pull request merged**
