### PR TITLE
Version bump to mark stable

### PR DESCRIPTION
**Pull request by ghost**
As discussed in #22, bumps version to 1.0.0 and marks stable. To be merged ahead of repo push.

### CODE REVIEW

**Comment by marcelveldt** [comment]
Current repo version has been tested for over a week now on several 3th party repos, so far no issues reported. Go ahead with the repo push ?

**Comment by ghost** [comment]
:-1: We don't want to break Nox 5 for once, so I just gave it a quick test and it looks suspiciously like the 'Just Select' method (used by Nox 5 for the main menu items) isn't correctly returning actions. Not sure why as I didn't think that code has been touched, but I'll debug this evening. Once thats fixed, though, and confirmed the rest of Nox 5 is working correctly, should be good for repo push.

**Comment by ghost** [comment]
Ignore me - I'd forgotten I'd hacked Nox 5 to use the Just Select Widgets method so I could quickly test it :blush: 

Yes, I think we're good for a repo push.

**Comment by ghost** [comment]
@marcelveldt you're obviously busy with real life at the moment. I've studiously avoided the Kodi mailing list since returning to Kodi scripting so far, but if you're too busy to deal with requesting the update on the repo, let me know and I'll face the fear and deal with it myself ;)

**Comment by ghost** [comment]
I don't have time to do this until Tuesday eve at earliest, but the suggestion coming from the forum is that the script focuses GUI 211 when the shortcuts are loaded - potentially with an override allowing the skin to select 303 or 304 if that is appropriate to the skin - before a repo push. See conversation from http://forum.kodi.tv/showthread.php?tid=178294&pid=2186091#pid2186091 onwards.

**Comment by marcelveldt** [comment]
I can/will do the repo push tonight, no problem. My internet connection got broken so I was offline for a couple of days :-)

About the focus of the control. I included some method for that in skinhelper.

RunScript(script.skin.helper.service,action=setfocus,control=201)

**Comment by marcelveldt** [comment]
Decided to not include the focus of control in the script at this time because that could possibly break other use cases in other skins. Best to leave it as is for now and let the skinner decide what control to give focus: They can use the delayed focus method in skinhelper for that or just focus an already existing control in their xml.

BTW: Another valid method is to set the window onload to focus a hidden button.
Set the onfocus of that hidden button to perform any action you like. This will prevent errors in the log and is more fail safe.

Examples in confluence skin startup.xml or Titan's home.xml

**Pull request merged**
