### PR TITLE
fixed icon assignment dialog not saving changes

### PR DESCRIPTION
**Pull request by marcelveldt**

### CODE REVIEW

**Comment by BigNoid** [comment]
@marcelveldt please squash the 2 commits.
@phil65 could you do the review?

**Comment by phil65** [comment]
only looked at diff, it´s safe to pull.

**Comment by marcelveldt** [comment]
thanks phil, where do you want me to commit any issues or pull requests ? The copy of the skinshortcuts script in BigNoid GitHub or yours ? Also, who's going to push any significant updates of the script to the kodi repo ?

**Comment by phil65** [comment]
I don´t mind, you can take BigNoid´s one for now. Doesnt really matter for us.

**Comment by marcelveldt** [comment]
okay thanks, I will close the PR on your fork and do the PR's on BigNoid's main version.
Thanks guys for keeping this script alive.

**Comment by BigNoid** [comment]
@marcelveldt please squash the commits, thx.

**Comment by marcelveldt** [comment]
okay, forgive me my bad english but by squasing I think you mean to merge the 3 commits into 1.
Done that and will send you a new fresh PR with only one commit that fixes the problem with the thumbnail dialog. Thx

**Pull request closed without merging**
