### PR TITLE
Krypton hotfix

### PR DESCRIPTION
**Pull request by ghost**
As suggested by @phil65, this adds a 'definition' element alongside the existing 'name' element for future Krypton compatibility. Already confirmed Jarvis will safely ignore the new attrib. Awaiting test builds - http://jenkins.kodi.tv/view/Helpers/job/BuildMulti-PR-Manually/202/ - to confirm that Krypton will accept both attributes. Once I've tested that, I will merge.

@marcelveldt Phil is suggesting this as a quick 'hotfix' so are you able to request a repo update once this is merged?

### CODE REVIEW

**Comment by phil65** [comment]
"definition", not "description" ;)

**Comment by ghost** [comment]
My eye test is next week ;)

**Comment by marcelveldt** [comment]
Sure, can do the repo request.

What is this new attribute for ?
Did I miss something ?

**Comment by ghost** [comment]
http://forum.kodi.tv/showthread.php?tid=259585

**Comment by marcelveldt** [comment]
Thanks, all clear now.Let's wait if it gets merged.

**Comment by phil65** [comment]
We should probably merge this first before the kodi merge. ;) It shouldnt hurt and I am quite sure that the PR will come through. (all team skinners agreed on that)

**Comment by marcelveldt** [comment]
Sorry, it's getting late here. That's what I meant ;-)

Let's do a quick test with the test build, if it looks fine, merge it in and request the update to the kodi repo.

**Comment by phil65** [comment]
http://mirrors.kodi.tv/test-builds/osx/x86_64/
f33813b

**Comment by ghost** [comment]
I presume it needs time to spread out to the mirrors, but right now I'm getting a 404 Not Found (http://ftp.halifax.rwth-aachen.de/xbmc/test-builds/osx/x86_64/kodi-20160211-f33813b--x86_64.dmg). I'll try again in half an hour or so and, if its still not working, will look in the morning :)

**Comment by phil65** [comment]
that might indeed be the case.

**Comment by ghost** [comment]
Can confirm the test build plays nicely with the dual attrib.

**Comment by phil65** [comment]
thx!

**Comment by marcelveldt** [comment]
OK, I discussed with ronie to also include a fix for the missing includes to prevent warnings in the logs, so I will fix that too and push this to the kodi repo asap.

**Comment by ghost** [comment]
With discussion about specific implementation on the forum, it feels like it would be sensible to confirm that the final attrib will be 'definition', and that the attrib will be changes on the definition of an include rather than the usage of an include with params before pushing to repo.

**Pull request merged**
