### PR TITLE
Doc update : $PARAM

### PR DESCRIPTION
**Pull request by Jayz2K**
Added documentation for moving properties into an include using $PARAM.

### CODE REVIEW

**Comment by Jayz2K** [comment]
@Ignoble61 Sorry for the 'tests' commits, I didn't think it will take them all. I'm not that familiar with the git doc's typo so made some tests before. PR done. I can refork it and make it clean IYW, just let me know.

**Comment by ghost** [comment]
Thanks so much for the docs. Are you familiar with squashing commits from a command line? (It's easier than it sounds!)

git rebase -i HEAD~7

In the text editor that opens, change the 'pick' of all but the first line to 'f' (fixup) and save. Then do a force push:-

git push -f

That will squash it all down to a single commit. You may also want to reword ('r' rather than 'pick') the first commit. If you do that, you'll get a second text editor opening up to change the commit message.

(*nix platforms tend to use vi as the text editor - press i to begin editing, make the changes, hit 'Esc', then type ':wq' to write and quit)

**Comment by Jayz2K** [comment]
YW, Honestly, I'm using github for Windows. Never used the command lines ...

**Comment by ghost** [comment]
As I say, it is easier than it sounds ;) Obviously we'd prefer not to pull 7 commits for a single change, so if you'd prefer to refork (or add a new branch based on BigNoid/master), redo the change and re-PR, that's fine too. Another possibility is to temporarily add me as a collaborator on your fork and I'll do the squash. Whatever's best for you :)

**Comment by phil65** [comment]
@Ignoble61 you can do that on your repo, too ;) Just add @Jayz2K as a remote, check out his master branch, squash and push to a branch on your own repo.

**Comment by ghost** [comment]
And I'm sure that's easier than it sounds, too :P

I can do that if that's preferable to you, @Jayz2K

**Comment by ghost** [comment]
OK, all done. Thanks again for the docs update :)

**Comment by Jayz2K** [comment]
Glad to help. Sorry again for all those dummy commits. Now I know that they're all taken while PR, I will take more care about it next time. And will make some reading about the squash command.

**Pull request merged**
