### PR TITLE
Add requires and templateOnly attribs to custom properties

### PR DESCRIPTION
**Pull request by ghost**
In the Aeon MadNox implementation of Skin Shortcuts, the amount of properties now being written to the main menu has become an issue (causing missing artwork on the home page). This implements two changes which can be used by skins to reduce the number of properties being written to the includes file:-

(1) 'requires' element for custom properties - lets another property be required to be present in the menu for this property to be added to it. E.g. custom widget properties can require the Skin Shortcuts-added 'widget' property

(2) 'templateonly' element for custom properties - with skins using templates, many properties are only useful within the templates. This lets these properties be specified, and then not written to the includes file.

@marcelveldt as this changes how menus are built, how fallbacks are added, and completely how additional properties are handled in the management dialog, if its possible to get this out for testing it would be appreciated. However, as only MadNox will be using it for the foreseeable (and my understanding is MadNox will have its own testing period when the Skin Shortcuts integration is ready), it's not essential if it causes you trouble :smile:

### CODE REVIEW

**Comment by marcelveldt** [comment]
I will put this on the beta repo tonight, will allow us for some real life testing.

**Comment by marcelveldt** [comment]
OK, it's now on the beta repo.
Can we have a feature freeze for a couple of days (bugfix only) so we can get a new stable version out early next week ?

**Comment by ghost** [comment]
:+1: for a feature freeze, and thanks for the merge + beta :)

**Comment by marcelveldt** [comment]
One issue discovered on the forums.. Set thumbnail is no longer working for submenus

**Comment by ghost** [comment]
Do you know if thats gui 306 or 311?

**Comment by ghost** [comment]
OK, spotted what's likely causing it to 'no longer work' - I'll provide a PR shortly.

**Pull request merged**
