### PR TITLE
Template and widget selection improvements

### PR DESCRIPTION
**Pull request by ghost**
Improvement to templates - $SKINSHORTCUT[] properties no longer need be the only thing in a control elements text or attribute. Now they will happily live alongside other text, and also allows multiple $SKINSHORTCUT[] in a control element.

Also bump version to 0.5.4.

@marcelveldt, do you have time to cast a quick eye over the changes? Cheers.

### CODE REVIEW

**Comment by ghost** [comment]
As it's also a relatively minor change, I've pushed an additional commit for a widget change to the PR.

This commit adds the option to select program plugins as a widget via the new `<content>addon-program-plugin</content>`. Also fixes an issue where programs without a xbmc.pluginsource entry point weren't being added to the available shortcuts and removes the workaround that was in place.

As this is a feature requested by tomer on the forums (and as I'm not aware that they are on GitHub) I'll ping them on the forums to see that this works for them. Would be good to get their confirmation before it gets merged.

Closes #65

**Comment by marcelveldt** [comment]
Tested the code, working fine. Also that tomer guy reported that it's working

**Comment by ghost** [comment]
Cheers to you and tomer (where did he report that its working, btw? Seen nothing in the skin shortcuts thread...?)

**Comment by marcelveldt** [comment]
http://forum.kodi.tv/showthread.php?tid=235676&pid=2109291#pid2109291

**Comment by ghost** [comment]
Ah, I don't routinely follow the skin helper thread :) (and I don't think Tomer fully gets the difference between the two scripts ;0)

**Comment by marcelveldt** [comment]
haha, yeah well good thing I noticed his comment than

**Comment by ghost** [comment]
Absolutely :)

**Pull request merged**
