### PR TITLE
Add visibleoverride

### PR DESCRIPTION
**Pull request by ghost**
Adds new `<visibleoverride />`, to allow running a different command if the automatic visibility condition doesn't match. As requested on the forum, so will ask originator to test.

Also contains updates to documentation, for everything added to this version so far.

### CODE REVIEW

**Comment by sualfred** [comment]
Just to add my reply here, too:
Works great. Looking forward to see it merged. Thanks.

**Comment by ghost** [comment]
As it's a comparatively major change in behaviour, I'll give it 24 hours for anyone to raise any objections before merging.

**Comment by marcelveldt** [comment]
np in merging it in, good for a new beta build

**Comment by ghost** [comment]
Cheers

**Pull request merged**
