### PR TITLE
If no label, redirect GUI 307 to 401

### PR DESCRIPTION
**Pull request by ghost**
When changing action in management dialog (GUI 307), if the shortcut being changed doesn't have a label the script will now redirect to select shortcut (GUI 401).

As the script will only save user shortcuts with a label (the default label of `<None>` is used to decide whether to save a shortcut), if the user selects 'Change action' on a new shortcut their selected shortcut won't be saved unless they also manually edit the label. By redirecting to 401 in this instance, the label will be set when they select their action and so the shortcut will be saved.

@marcelveldt can you confirm this doesn't interfere with what your aims are for the updated change action function :) Cheers.

### CODE REVIEW

**Comment by ghost** [comment]
Can I assume no-one has any issues with this being merged? :)

**Comment by marcelveldt** [comment]
no problems here ;-)

**Comment by ghost** [comment]
Good thing, I was literally about to merge it myself ;)

**Comment by marcelveldt** [comment]
hehe, I didn't notice the PR sooner

**Pull request merged**
