### PR TITLE
Update Italian language

### PR DESCRIPTION
**Pull request by iz8mbw**
Update whole strings.po for Italian language

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
Thanks for this. Can you please confirm 32032 is correctly translated (seems to be partially reverting translation to English), and correct 32096 (translation removed, original string truncated and missing closing quotation mark). Cheers.

**Review by iz8mbw — COMMENTED** [review]
corrected 32096

**Comment by iz8mbw** [comment]
32032 is OK, corrected 32096

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
👍

**Pull request merged**
