### PR TITLE
Extend property based on multiple elements to require all rules

### PR DESCRIPTION
**Pull request by ghost**
As requested, allows matching property based on multiple elements to require all the rules specified to match, rather than any.

See new `<match />` element in example below.

```
<property name="leftartwork" propertyValue="5">
    <rule tag="property" attribute="name|widgetStyle" value="Panel" />
    <rule tag="property" attribute="name|widgetArt" value="Poster" />
    <rule tag="property" attribute="name|widgetCase" value="Glass" />
    <match>all</match
</property>
```

Pinging @mistervee to test :)

### CODE REVIEW

**Comment by mistervee** [comment]
@Ignoble61 Thanks. Working well.

The one thing I did notice is if I do this and the first multiple property element is matched the second value is used. I actually expected the first property match to be used and the script to ignore the second.

`<property name="leftart" propertyValue="4.5">
`
`<rule tag="property" attribute="name|widgetArt" value="Poster" />
`
`<rule tag="property" attribute="name|widgetCase" value="Case" />
`
`<match>all</match>
`
`</property>
`
`<property name="leftart">2.5</property>`

Not a big deal for me, I can work with it as you have designed.

**Comment by ghost** [comment]
It should indeed only match the first one. I'll try and track down that bug tonight, otherwise I'll push a fix tomorrow evening.

**Comment by ghost** [comment]
@mistervee I've reviewed the code and can't just see where it's going wrong, so can you please try again with the latest commit (which adds extra logging) and post a link to a log - with Skin Shortcuts own debug logging option enabled. Hopefully that will at the very least track down where the issue is. Cheers.

**Comment by mistervee** [comment]
http://pastebin.com/7La1j7Pv
here is the log.

The logging addition has seemed to of broken the template.

Here is the madnox template xml I am working on
https://onedrive.live.com/redir?resid=AE1918D112D1916C!5362&authkey=!AB3ZDT1iAp86yVA&ithint=file%2cxml

**Comment by mistervee** [comment]
The code in question is around line 500.

Only widget 1, Panel Style, Poster and square has the new code.

**Comment by ghost** [comment]
Hopefully spotted the issue - I didn't take into account that the script has to check each element of the menu item individually to see if it has the same property as the rule wants to match against, so the code was thinking that the rules weren't matching far too soon.

If the fix doesn't work, another debug log please :)

By the way - and assuming I've done my job correctly, and its entirely possible I haven't - you can access your properties directly in Python snippets by name, so

`$PYTHON[((300 - int($SKINSHORTCUTS[containerheight])) / 2) + 454]`

should be able to be just

`$PYTHON[((300 - int(containerheight)) / 2) + 454]`

**Comment by mistervee** [comment]
http://pastebin.com/wp4nS1Ee

The script seems to stall on building the properties. It only matches the 1st one and then no other properties build after.

**Comment by ghost** [comment]
OK, one more attempt now uploaded, and when it still doesn't work I'll look properly into it tomorrow :)

(Thanks for the thorough testing, by the way!)

**Comment by mistervee** [comment]
Working great now.

Sadly this does not work without the $SKINSHORTCUTS
`$PYTHON[((300 - int(containerheight)) / 2) + 454]`

No trouble at all testing this out. A big thanks for incorporating the feature.

**Comment by ghost** [comment]
I'll add that to my list of things to debug for another day ;)

**Pull request merged**
