### PR TITLE
Remove old functions

### PR DESCRIPTION
**Pull request by ghost**
Removes all .shortcut file compatibility (should only affect Nox5 + variants)
Removes ability for list to be filled with controls to launch management dialog (I don't believe these methods are in use by any skin)

@BigNoid - as these changes should only affect your skin + variants, do you want the honour of merging when you feel comfortable (idk if you prefer to wait for your change to .DATA.xml files - #22 - to hit the repo before this gets merged)?

### CODE REVIEW

**Comment by BigNoid** [comment]
@Ignoble61 Thanks, I'll do a pull request shortly for Nox. If this change can wait till then it would be highly appreciated. I'll merge this then right after that.
I see removing the old functions saves quite a lot of code!

**Comment by ghost** [comment]
No rush at all for this getting merged from my pov. Just nice to be able to delete some of the old code ;)

**Comment by ghost** [comment]
Found one other skin from a quick repo search that also uses the .shortcuts files - would be nice if this didn't get merged until that skin has time to update to the new format as well :) (See skin.mimic issue referenced above)

**Comment by marcelveldt** [comment]
Mimic has changed the shortcuts method on your request so that's all fine now. As soon as BigNoid has published the update of his skin to the repo, this thing can be merged too, right ?

**Comment by ghost** [comment]
Right.

**Comment by BigNoid** [comment]
This can be merged now, but must be rebased i think.

**Comment by ghost** [comment]
Rebased and merged, cheers.

**Pull request merged**
