### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by ghost**
Updates and markdown's all the documentation, as well as moves each topic into individual files. Also corrects some out of date or just plain wrong information.

Hopefully makes the documentation a hell of a lot easier to read, and means it should be far easier to tell people to RTFM ;)

### CODE REVIEW

**Comment by marcelveldt** [comment]
Wow! You must have had some spare time left ;-)
Thanks for your work on this, I'm sure a lot of skinners will appreciate this and it might even attract more skins to use skinshortcuts. Well done!

**Comment by jingai** [comment]
Definitely much appreciated.  It's all much more clear now :)

**Comment by ghost** [comment]
> Wow! You must have had some spare time left ;-)

I haven't had spare time because I've been working on getting this done :wink: Cheers for the merge :+1:

**Comment by marcelveldt** [comment]
haha! Really great work

**Pull request merged**
