### PR TITLE
make sure library paths end with trailing slash

### PR DESCRIPTION
**Pull request by marcelveldt**
@Ignoble61 

My local fork was messed up so after a few hours of trying to fix it with rebasing and squashing I gave up and just reforked :-)

Well, here finally is the PR for the trailing slash.
I have tested this for some weeks now and no issues discovered.

As you're waiting for a new repo push, merge this one in, build a new beta and push to stable at Wednesday or Thursday ?

### CODE REVIEW

**Comment by ghost** [comment]
Many thanks for this :)

Assuming no bugs come to light in the beta, a repo push towards the end of the week sounds great.

**Comment by ghost** [comment]
@marcelveldt Did this go onto the beta repo? If so, and assuming you've heard as few bug reports as I have, any objections to the push?

Now the method has changed and pushes no longer have to go through the mailing list, are you still happy leading the repo push or would you prefer I did it?

**Comment by marcelveldt** [comment]
Yes it did and no issues have been reported :-)

New repo push would be a great idea. No problem if you want to take over the repo pushes again.
I also have no problem doing the rpeo pushes so it's your call ;-)

**Comment by ghost** [comment]
What's you're time like to do it at the moment? I'm enjoying snooker this evening (and still need to read up on the new method), and then preparing for next weeks business trip the next couple of days, so I can do it Thursday, or if you have the time to do it before then...?

**Comment by marcelveldt** [comment]
I can do this tomorrow evening

**Comment by ghost** [comment]
Can I leave it with you, then. If real life gets in the way, or if changes are required (I understand scripts are being scrutinised a little closer than in the past), I'll do what needs to be done on Thursday.

**Comment by ghost** [comment]
I really am going to have to leave this to you, if that's alright. As the snooker finished early, I thought I'd give it a go but my every attempt to clone the xbmc-scripts repo (isengard branch) shows several untracked files form script.tvtunes which I can't stash, delete or, well, do anything with - they're stopping me from creating a branch or pushing any changes so, right now, I'm completely unable to make a PR directly to the relevant repo :confused:

**Pull request merged**
